// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmonova/cosmonova/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryRetrieveValueRequest struct {
	QueryId   string `protobuf:"bytes,1,opt,name=queryId,proto3" json:"queryId,omitempty"`
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *QueryRetrieveValueRequest) Reset()         { *m = QueryRetrieveValueRequest{} }
func (m *QueryRetrieveValueRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRetrieveValueRequest) ProtoMessage()    {}
func (*QueryRetrieveValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{2}
}
func (m *QueryRetrieveValueRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRetrieveValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRetrieveValueRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRetrieveValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRetrieveValueRequest.Merge(m, src)
}
func (m *QueryRetrieveValueRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRetrieveValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRetrieveValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRetrieveValueRequest proto.InternalMessageInfo

func (m *QueryRetrieveValueRequest) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

func (m *QueryRetrieveValueRequest) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type QueryRetrieveValueResponse struct {
	Report *Report `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
}

func (m *QueryRetrieveValueResponse) Reset()         { *m = QueryRetrieveValueResponse{} }
func (m *QueryRetrieveValueResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRetrieveValueResponse) ProtoMessage()    {}
func (*QueryRetrieveValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{3}
}
func (m *QueryRetrieveValueResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRetrieveValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRetrieveValueResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRetrieveValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRetrieveValueResponse.Merge(m, src)
}
func (m *QueryRetrieveValueResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRetrieveValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRetrieveValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRetrieveValueResponse proto.InternalMessageInfo

func (m *QueryRetrieveValueResponse) GetReport() *Report {
	if m != nil {
		return m.Report
	}
	return nil
}

type QueryRetrieveValueAllRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRetrieveValueAllRequest) Reset()         { *m = QueryRetrieveValueAllRequest{} }
func (m *QueryRetrieveValueAllRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRetrieveValueAllRequest) ProtoMessage()    {}
func (*QueryRetrieveValueAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{4}
}
func (m *QueryRetrieveValueAllRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRetrieveValueAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRetrieveValueAllRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRetrieveValueAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRetrieveValueAllRequest.Merge(m, src)
}
func (m *QueryRetrieveValueAllRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRetrieveValueAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRetrieveValueAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRetrieveValueAllRequest proto.InternalMessageInfo

func (m *QueryRetrieveValueAllRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryRetrieveValueAllResponse struct {
	Report     []Report            `protobuf:"bytes,1,rep,name=report,proto3" json:"report"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRetrieveValueAllResponse) Reset()         { *m = QueryRetrieveValueAllResponse{} }
func (m *QueryRetrieveValueAllResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRetrieveValueAllResponse) ProtoMessage()    {}
func (*QueryRetrieveValueAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{5}
}
func (m *QueryRetrieveValueAllResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRetrieveValueAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRetrieveValueAllResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRetrieveValueAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRetrieveValueAllResponse.Merge(m, src)
}
func (m *QueryRetrieveValueAllResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRetrieveValueAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRetrieveValueAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRetrieveValueAllResponse proto.InternalMessageInfo

func (m *QueryRetrieveValueAllResponse) GetReport() []Report {
	if m != nil {
		return m.Report
	}
	return nil
}

func (m *QueryRetrieveValueAllResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAllRequestsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetAllRequestsRequest) Reset()         { *m = QueryGetAllRequestsRequest{} }
func (m *QueryGetAllRequestsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllRequestsRequest) ProtoMessage()    {}
func (*QueryGetAllRequestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{6}
}
func (m *QueryGetAllRequestsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllRequestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllRequestsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllRequestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllRequestsRequest.Merge(m, src)
}
func (m *QueryGetAllRequestsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllRequestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllRequestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllRequestsRequest proto.InternalMessageInfo

func (m *QueryGetAllRequestsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAllRequestsResponse struct {
	AllRequests []DataRequest       `protobuf:"bytes,1,rep,name=allRequests,proto3" json:"allRequests"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetAllRequestsResponse) Reset()         { *m = QueryGetAllRequestsResponse{} }
func (m *QueryGetAllRequestsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllRequestsResponse) ProtoMessage()    {}
func (*QueryGetAllRequestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{7}
}
func (m *QueryGetAllRequestsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllRequestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllRequestsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllRequestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllRequestsResponse.Merge(m, src)
}
func (m *QueryGetAllRequestsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllRequestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllRequestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllRequestsResponse proto.InternalMessageInfo

func (m *QueryGetAllRequestsResponse) GetAllRequests() []DataRequest {
	if m != nil {
		return m.AllRequests
	}
	return nil
}

func (m *QueryGetAllRequestsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetRequestCountRequest struct {
	QueryId string `protobuf:"bytes,1,opt,name=queryId,proto3" json:"queryId,omitempty"`
}

func (m *QueryGetRequestCountRequest) Reset()         { *m = QueryGetRequestCountRequest{} }
func (m *QueryGetRequestCountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRequestCountRequest) ProtoMessage()    {}
func (*QueryGetRequestCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{8}
}
func (m *QueryGetRequestCountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRequestCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRequestCountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRequestCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRequestCountRequest.Merge(m, src)
}
func (m *QueryGetRequestCountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRequestCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRequestCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRequestCountRequest proto.InternalMessageInfo

func (m *QueryGetRequestCountRequest) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

type QueryGetRequestCountResponse struct {
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *QueryGetRequestCountResponse) Reset()         { *m = QueryGetRequestCountResponse{} }
func (m *QueryGetRequestCountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRequestCountResponse) ProtoMessage()    {}
func (*QueryGetRequestCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{9}
}
func (m *QueryGetRequestCountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRequestCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRequestCountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRequestCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRequestCountResponse.Merge(m, src)
}
func (m *QueryGetRequestCountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRequestCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRequestCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRequestCountResponse proto.InternalMessageInfo

func (m *QueryGetRequestCountResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type QueryGetRequestDataRequest struct {
	QId string `protobuf:"bytes,1,opt,name=qId,proto3" json:"qId,omitempty"`
}

func (m *QueryGetRequestDataRequest) Reset()         { *m = QueryGetRequestDataRequest{} }
func (m *QueryGetRequestDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRequestDataRequest) ProtoMessage()    {}
func (*QueryGetRequestDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{10}
}
func (m *QueryGetRequestDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRequestDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRequestDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRequestDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRequestDataRequest.Merge(m, src)
}
func (m *QueryGetRequestDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRequestDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRequestDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRequestDataRequest proto.InternalMessageInfo

func (m *QueryGetRequestDataRequest) GetQId() string {
	if m != nil {
		return m.QId
	}
	return ""
}

type QueryGetRequestDataResponse struct {
	RequestData *Requests `protobuf:"bytes,1,opt,name=requestData,proto3" json:"requestData,omitempty"`
}

func (m *QueryGetRequestDataResponse) Reset()         { *m = QueryGetRequestDataResponse{} }
func (m *QueryGetRequestDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRequestDataResponse) ProtoMessage()    {}
func (*QueryGetRequestDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd23b69b4e268c9a, []int{11}
}
func (m *QueryGetRequestDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRequestDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRequestDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRequestDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRequestDataResponse.Merge(m, src)
}
func (m *QueryGetRequestDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRequestDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRequestDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRequestDataResponse proto.InternalMessageInfo

func (m *QueryGetRequestDataResponse) GetRequestData() *Requests {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmonova.cosmonova.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmonova.cosmonova.QueryParamsResponse")
	proto.RegisterType((*QueryRetrieveValueRequest)(nil), "cosmonova.cosmonova.QueryRetrieveValueRequest")
	proto.RegisterType((*QueryRetrieveValueResponse)(nil), "cosmonova.cosmonova.QueryRetrieveValueResponse")
	proto.RegisterType((*QueryRetrieveValueAllRequest)(nil), "cosmonova.cosmonova.QueryRetrieveValueAllRequest")
	proto.RegisterType((*QueryRetrieveValueAllResponse)(nil), "cosmonova.cosmonova.QueryRetrieveValueAllResponse")
	proto.RegisterType((*QueryGetAllRequestsRequest)(nil), "cosmonova.cosmonova.QueryGetAllRequestsRequest")
	proto.RegisterType((*QueryGetAllRequestsResponse)(nil), "cosmonova.cosmonova.QueryGetAllRequestsResponse")
	proto.RegisterType((*QueryGetRequestCountRequest)(nil), "cosmonova.cosmonova.QueryGetRequestCountRequest")
	proto.RegisterType((*QueryGetRequestCountResponse)(nil), "cosmonova.cosmonova.QueryGetRequestCountResponse")
	proto.RegisterType((*QueryGetRequestDataRequest)(nil), "cosmonova.cosmonova.QueryGetRequestDataRequest")
	proto.RegisterType((*QueryGetRequestDataResponse)(nil), "cosmonova.cosmonova.QueryGetRequestDataResponse")
}

func init() { proto.RegisterFile("cosmonova/cosmonova/query.proto", fileDescriptor_fd23b69b4e268c9a) }

var fileDescriptor_fd23b69b4e268c9a = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xcd, 0x4e, 0x1b, 0x3b,
	0x14, 0xc7, 0x33, 0x7c, 0x04, 0x61, 0x74, 0xef, 0x45, 0x86, 0x05, 0x77, 0x02, 0x21, 0x9a, 0xab,
	0x4b, 0x68, 0x2b, 0xc6, 0x24, 0xb4, 0x6a, 0x51, 0x17, 0x15, 0xb4, 0x2a, 0x65, 0x07, 0x53, 0xa9,
	0x8b, 0x2e, 0x1a, 0x19, 0xe2, 0x8e, 0x22, 0x25, 0xe3, 0xc9, 0xd8, 0x89, 0x8a, 0x10, 0x52, 0xd5,
	0x27, 0xa8, 0xd4, 0x37, 0x68, 0x37, 0x55, 0x57, 0x48, 0x7d, 0x09, 0x96, 0x48, 0xdd, 0x74, 0x55,
	0x55, 0xd0, 0x07, 0xe8, 0x23, 0x54, 0x63, 0x9f, 0x64, 0x12, 0xe2, 0x7c, 0x20, 0xb1, 0x73, 0x3c,
	0xe7, 0x7f, 0xce, 0x6f, 0xfe, 0x3e, 0xc7, 0x19, 0xb4, 0x7c, 0xc8, 0x45, 0x8d, 0x07, 0xbc, 0x49,
	0x49, 0xb2, 0xaa, 0x37, 0x58, 0x74, 0xe4, 0x86, 0x11, 0x97, 0x1c, 0xcf, 0xb5, 0xb7, 0xdd, 0xf6,
	0xca, 0x9e, 0xf7, 0xb9, 0xcf, 0xd5, 0x73, 0x12, 0xaf, 0x74, 0xa8, 0xbd, 0xe8, 0x73, 0xee, 0x57,
	0x19, 0xa1, 0x61, 0x85, 0xd0, 0x20, 0xe0, 0x92, 0xca, 0x0a, 0x0f, 0x04, 0x3c, 0xbd, 0xad, 0xe4,
	0x82, 0x1c, 0x50, 0xc1, 0x74, 0x05, 0xd2, 0x2c, 0x1c, 0x30, 0x49, 0x0b, 0x24, 0xa4, 0x7e, 0x25,
	0x50, 0xc1, 0x10, 0x9b, 0x33, 0x51, 0x85, 0x34, 0xa2, 0x35, 0x31, 0x28, 0x22, 0x62, 0x21, 0x8f,
	0x24, 0x44, 0xac, 0x98, 0x22, 0xca, 0x54, 0xd2, 0x52, 0xc4, 0xea, 0x0d, 0x26, 0x5a, 0x71, 0x8e,
	0x39, 0x93, 0x0a, 0x81, 0x6a, 0xce, 0x3c, 0xc2, 0xfb, 0x31, 0xf1, 0x9e, 0x42, 0xf0, 0xf4, 0x43,
	0x67, 0x0f, 0xcd, 0x75, 0xed, 0x8a, 0x90, 0x07, 0x82, 0xe1, 0x4d, 0x94, 0xd6, 0xa8, 0x0b, 0x56,
	0xce, 0x5a, 0x9d, 0x29, 0x66, 0x5c, 0x83, 0x85, 0xae, 0x16, 0x6d, 0x4f, 0x9c, 0xfd, 0x58, 0x4e,
	0x79, 0x20, 0x70, 0x9e, 0xa3, 0x7f, 0x55, 0x46, 0x8f, 0xc9, 0xa8, 0xc2, 0x9a, 0xec, 0x05, 0xad,
	0x36, 0x18, 0x94, 0xc3, 0x0b, 0x68, 0x4a, 0xd9, 0xb6, 0x5b, 0x56, 0x89, 0xa7, 0xbd, 0xd6, 0x4f,
	0xbc, 0x88, 0xa6, 0x65, 0xa5, 0xc6, 0x84, 0xa4, 0xb5, 0x70, 0x61, 0x2c, 0x67, 0xad, 0x4e, 0x78,
	0xc9, 0x86, 0xb3, 0x8f, 0x6c, 0x53, 0x52, 0xa0, 0xdd, 0x40, 0x69, 0x6d, 0xdb, 0x40, 0x5a, 0x4f,
	0x85, 0x78, 0x10, 0xea, 0xbc, 0x46, 0x8b, 0xbd, 0x29, 0xb7, 0xaa, 0xd5, 0x16, 0xea, 0x53, 0x84,
	0x92, 0x33, 0x85, 0xc4, 0x2b, 0x3a, 0x9d, 0x70, 0xe3, 0x06, 0x70, 0x75, 0x8b, 0x41, 0x03, 0xb8,
	0x7b, 0xd4, 0x6f, 0xbd, 0xa6, 0xd7, 0xa1, 0x74, 0x3e, 0x59, 0x68, 0xa9, 0x4f, 0xa1, 0xc4, 0xec,
	0x36, 0xfe, 0xf8, 0x10, 0xfc, 0x96, 0xd9, 0x5a, 0x80, 0x77, 0xba, 0x20, 0xc7, 0x14, 0x64, 0x7e,
	0x28, 0xa4, 0xae, 0xdb, 0x45, 0x59, 0x06, 0x83, 0x77, 0x98, 0x4c, 0x3c, 0x10, 0x37, 0xed, 0xc5,
	0xa9, 0x85, 0x32, 0xc6, 0x32, 0xe0, 0xc4, 0x33, 0x34, 0x43, 0x93, 0x6d, 0xb0, 0x23, 0x67, 0xb4,
	0xe3, 0x09, 0x95, 0x14, 0x02, 0xc1, 0x93, 0x4e, 0xe9, 0xcd, 0x19, 0x73, 0x3f, 0x21, 0x86, 0xe4,
	0x8f, 0x79, 0x23, 0x90, 0x43, 0x1b, 0xda, 0xb9, 0x0b, 0xfd, 0xd5, 0x23, 0x84, 0x77, 0x9d, 0x47,
	0x93, 0x87, 0xf1, 0x86, 0xd2, 0x4d, 0x78, 0xfa, 0x87, 0xe3, 0x26, 0xe7, 0x00, 0xaa, 0x8e, 0x17,
	0xc5, 0xb3, 0x68, 0xbc, 0xde, 0xae, 0x14, 0x2f, 0x9d, 0x57, 0x3d, 0x78, 0x3a, 0x1e, 0x8a, 0x3c,
	0x42, 0x33, 0x51, 0xb2, 0x0d, 0x27, 0xb7, 0xd4, 0xa7, 0xbf, 0xe0, 0x30, 0x3a, 0x15, 0xc5, 0xdf,
	0x53, 0x68, 0x52, 0x15, 0xc0, 0x6f, 0x2d, 0x94, 0xd6, 0x03, 0x8f, 0xf3, 0xc6, 0x04, 0xbd, 0xb7,
	0x8b, 0xbd, 0x3a, 0x3c, 0x50, 0x83, 0x3a, 0xff, 0xbd, 0xfb, 0xf6, 0xeb, 0xc3, 0xd8, 0x12, 0xce,
	0x90, 0xfe, 0xd7, 0x26, 0xfe, 0x6a, 0xa1, 0xbf, 0xba, 0xa6, 0x08, 0xbb, 0xfd, 0x0b, 0x98, 0xee,
	0x1f, 0x9b, 0x8c, 0x1c, 0x0f, 0x5c, 0x5b, 0x8a, 0xeb, 0x21, 0xde, 0x24, 0xe6, 0x2b, 0x56, 0x6b,
	0x4a, 0xcd, 0x58, 0x44, 0x8e, 0xe1, 0xec, 0x4f, 0xc8, 0x71, 0xfb, 0xea, 0x3a, 0xc1, 0x5f, 0x2c,
	0x34, 0x7b, 0x75, 0xf6, 0x71, 0x61, 0x44, 0x90, 0x64, 0x4a, 0xec, 0xe2, 0x75, 0x24, 0x80, 0x4f,
	0x14, 0xfe, 0x2d, 0x9c, 0x1f, 0x01, 0xbf, 0x44, 0xab, 0x55, 0xfc, 0xd1, 0x42, 0x7f, 0x77, 0x0f,
	0x27, 0x1e, 0xe0, 0x99, 0xf1, 0xb6, 0xb0, 0xd7, 0x47, 0x17, 0x00, 0xe6, 0x9a, 0xc2, 0xcc, 0xe3,
	0xff, 0x8d, 0x98, 0x3e, 0x93, 0x31, 0x5b, 0xeb, 0x3f, 0x4f, 0xe0, 0x53, 0x0b, 0xfd, 0x73, 0x65,
	0xac, 0xf0, 0xe0, 0xa2, 0x86, 0xd1, 0xb5, 0x0b, 0xd7, 0x50, 0x00, 0xe7, 0x03, 0xc5, 0x59, 0xc4,
	0xeb, 0x7d, 0x39, 0x81, 0xb1, 0xa4, 0xa6, 0x39, 0x69, 0x08, 0xfc, 0x59, 0xfb, 0xda, 0x31, 0xa3,
	0x43, 0x7c, 0xed, 0x9d, 0x7e, 0x7b, 0x7d, 0x74, 0x01, 0xf0, 0x6e, 0x28, 0xde, 0x35, 0x7c, 0x67,
	0x28, 0x6f, 0xfc, 0x51, 0x41, 0x8e, 0xeb, 0xbb, 0xe5, 0x93, 0xed, 0x7b, 0x67, 0x17, 0x59, 0xeb,
	0xfc, 0x22, 0x6b, 0xfd, 0xbc, 0xc8, 0x5a, 0xef, 0x2f, 0xb3, 0xa9, 0xf3, 0xcb, 0x6c, 0xea, 0xfb,
	0x65, 0x36, 0xf5, 0x32, 0x93, 0x68, 0xdf, 0x74, 0xe4, 0x91, 0x47, 0x21, 0x13, 0x07, 0x69, 0xf5,
	0x99, 0xb1, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x80, 0x67, 0xce, 0xdb, 0x8e, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of RetrieveValue items.
	RetrieveValue(ctx context.Context, in *QueryRetrieveValueRequest, opts ...grpc.CallOption) (*QueryRetrieveValueResponse, error)
	// Queries a list of RetrieveValueAll items.
	RetrieveValueAll(ctx context.Context, in *QueryRetrieveValueAllRequest, opts ...grpc.CallOption) (*QueryRetrieveValueAllResponse, error)
	// Queries a list of GetAllRequests items.
	GetAllRequests(ctx context.Context, in *QueryGetAllRequestsRequest, opts ...grpc.CallOption) (*QueryGetAllRequestsResponse, error)
	// Queries a list of GetRequestCount items.
	GetRequestCount(ctx context.Context, in *QueryGetRequestCountRequest, opts ...grpc.CallOption) (*QueryGetRequestCountResponse, error)
	// Queries a list of GetRequestData items.
	GetRequestData(ctx context.Context, in *QueryGetRequestDataRequest, opts ...grpc.CallOption) (*QueryGetRequestDataResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmonova.cosmonova.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RetrieveValue(ctx context.Context, in *QueryRetrieveValueRequest, opts ...grpc.CallOption) (*QueryRetrieveValueResponse, error) {
	out := new(QueryRetrieveValueResponse)
	err := c.cc.Invoke(ctx, "/cosmonova.cosmonova.Query/RetrieveValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RetrieveValueAll(ctx context.Context, in *QueryRetrieveValueAllRequest, opts ...grpc.CallOption) (*QueryRetrieveValueAllResponse, error) {
	out := new(QueryRetrieveValueAllResponse)
	err := c.cc.Invoke(ctx, "/cosmonova.cosmonova.Query/RetrieveValueAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAllRequests(ctx context.Context, in *QueryGetAllRequestsRequest, opts ...grpc.CallOption) (*QueryGetAllRequestsResponse, error) {
	out := new(QueryGetAllRequestsResponse)
	err := c.cc.Invoke(ctx, "/cosmonova.cosmonova.Query/GetAllRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetRequestCount(ctx context.Context, in *QueryGetRequestCountRequest, opts ...grpc.CallOption) (*QueryGetRequestCountResponse, error) {
	out := new(QueryGetRequestCountResponse)
	err := c.cc.Invoke(ctx, "/cosmonova.cosmonova.Query/GetRequestCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetRequestData(ctx context.Context, in *QueryGetRequestDataRequest, opts ...grpc.CallOption) (*QueryGetRequestDataResponse, error) {
	out := new(QueryGetRequestDataResponse)
	err := c.cc.Invoke(ctx, "/cosmonova.cosmonova.Query/GetRequestData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of RetrieveValue items.
	RetrieveValue(context.Context, *QueryRetrieveValueRequest) (*QueryRetrieveValueResponse, error)
	// Queries a list of RetrieveValueAll items.
	RetrieveValueAll(context.Context, *QueryRetrieveValueAllRequest) (*QueryRetrieveValueAllResponse, error)
	// Queries a list of GetAllRequests items.
	GetAllRequests(context.Context, *QueryGetAllRequestsRequest) (*QueryGetAllRequestsResponse, error)
	// Queries a list of GetRequestCount items.
	GetRequestCount(context.Context, *QueryGetRequestCountRequest) (*QueryGetRequestCountResponse, error)
	// Queries a list of GetRequestData items.
	GetRequestData(context.Context, *QueryGetRequestDataRequest) (*QueryGetRequestDataResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) RetrieveValue(ctx context.Context, req *QueryRetrieveValueRequest) (*QueryRetrieveValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveValue not implemented")
}
func (*UnimplementedQueryServer) RetrieveValueAll(ctx context.Context, req *QueryRetrieveValueAllRequest) (*QueryRetrieveValueAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveValueAll not implemented")
}
func (*UnimplementedQueryServer) GetAllRequests(ctx context.Context, req *QueryGetAllRequestsRequest) (*QueryGetAllRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRequests not implemented")
}
func (*UnimplementedQueryServer) GetRequestCount(ctx context.Context, req *QueryGetRequestCountRequest) (*QueryGetRequestCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequestCount not implemented")
}
func (*UnimplementedQueryServer) GetRequestData(ctx context.Context, req *QueryGetRequestDataRequest) (*QueryGetRequestDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequestData not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonova.cosmonova.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RetrieveValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRetrieveValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RetrieveValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonova.cosmonova.Query/RetrieveValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RetrieveValue(ctx, req.(*QueryRetrieveValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RetrieveValueAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRetrieveValueAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RetrieveValueAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonova.cosmonova.Query/RetrieveValueAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RetrieveValueAll(ctx, req.(*QueryRetrieveValueAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAllRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAllRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonova.cosmonova.Query/GetAllRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAllRequests(ctx, req.(*QueryGetAllRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetRequestCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRequestCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRequestCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonova.cosmonova.Query/GetRequestCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRequestCount(ctx, req.(*QueryGetRequestCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetRequestData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRequestDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRequestData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonova.cosmonova.Query/GetRequestData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRequestData(ctx, req.(*QueryGetRequestDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmonova.cosmonova.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "RetrieveValue",
			Handler:    _Query_RetrieveValue_Handler,
		},
		{
			MethodName: "RetrieveValueAll",
			Handler:    _Query_RetrieveValueAll_Handler,
		},
		{
			MethodName: "GetAllRequests",
			Handler:    _Query_GetAllRequests_Handler,
		},
		{
			MethodName: "GetRequestCount",
			Handler:    _Query_GetRequestCount_Handler,
		},
		{
			MethodName: "GetRequestData",
			Handler:    _Query_GetRequestData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmonova/cosmonova/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRetrieveValueRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRetrieveValueRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRetrieveValueRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x10
	}
	if len(m.QueryId) > 0 {
		i -= len(m.QueryId)
		copy(dAtA[i:], m.QueryId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.QueryId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRetrieveValueResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRetrieveValueResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRetrieveValueResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Report != nil {
		{
			size, err := m.Report.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRetrieveValueAllRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRetrieveValueAllRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRetrieveValueAllRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRetrieveValueAllResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRetrieveValueAllResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRetrieveValueAllResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Report) > 0 {
		for iNdEx := len(m.Report) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Report[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAllRequestsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllRequestsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllRequestsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAllRequestsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllRequestsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllRequestsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AllRequests) > 0 {
		for iNdEx := len(m.AllRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRequestCountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRequestCountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRequestCountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.QueryId) > 0 {
		i -= len(m.QueryId)
		copy(dAtA[i:], m.QueryId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.QueryId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRequestCountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRequestCountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRequestCountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRequestDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRequestDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRequestDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.QId) > 0 {
		i -= len(m.QId)
		copy(dAtA[i:], m.QId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.QId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRequestDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRequestDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRequestDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestData != nil {
		{
			size, err := m.RequestData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRetrieveValueRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.QueryId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovQuery(uint64(m.Timestamp))
	}
	return n
}

func (m *QueryRetrieveValueResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Report != nil {
		l = m.Report.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRetrieveValueAllRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRetrieveValueAllResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Report) > 0 {
		for _, e := range m.Report {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAllRequestsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAllRequestsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AllRequests) > 0 {
		for _, e := range m.AllRequests {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRequestCountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.QueryId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRequestCountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func (m *QueryGetRequestDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.QId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRequestDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestData != nil {
		l = m.RequestData.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRetrieveValueRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRetrieveValueRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRetrieveValueRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRetrieveValueResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRetrieveValueResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRetrieveValueResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Report", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Report == nil {
				m.Report = &Report{}
			}
			if err := m.Report.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRetrieveValueAllRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRetrieveValueAllRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRetrieveValueAllRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRetrieveValueAllResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRetrieveValueAllResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRetrieveValueAllResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Report", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Report = append(m.Report, Report{})
			if err := m.Report[len(m.Report)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllRequestsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllRequestsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllRequestsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllRequestsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllRequestsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllRequestsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllRequests = append(m.AllRequests, DataRequest{})
			if err := m.AllRequests[len(m.AllRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRequestCountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRequestCountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRequestCountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRequestCountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRequestCountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRequestCountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRequestDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRequestDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRequestDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRequestDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRequestDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRequestDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RequestData == nil {
				m.RequestData = &Requests{}
			}
			if err := m.RequestData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
