// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmonova/client/common_encoded_part.proto

package types

import (
	fmt "fmt"
	github_com_cometbft_cometbft_libs_bytes "github.com/cometbft/cometbft/libs/bytes"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CommonEncodedVotePart struct {
	SignedDataPrefix github_com_cometbft_cometbft_libs_bytes.HexBytes `protobuf:"bytes,1,opt,name=signed_data_prefix,json=signedDataPrefix,proto3,casttype=github.com/cometbft/cometbft/libs/bytes.HexBytes" json:"signed_data_prefix,omitempty"`
	SignedDataSuffix github_com_cometbft_cometbft_libs_bytes.HexBytes `protobuf:"bytes,2,opt,name=signed_data_suffix,json=signedDataSuffix,proto3,casttype=github.com/cometbft/cometbft/libs/bytes.HexBytes" json:"signed_data_suffix,omitempty"`
}

func (m *CommonEncodedVotePart) Reset()         { *m = CommonEncodedVotePart{} }
func (m *CommonEncodedVotePart) String() string { return proto.CompactTextString(m) }
func (*CommonEncodedVotePart) ProtoMessage()    {}
func (*CommonEncodedVotePart) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aa65ce86c9780ba, []int{0}
}
func (m *CommonEncodedVotePart) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommonEncodedVotePart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommonEncodedVotePart.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CommonEncodedVotePart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonEncodedVotePart.Merge(m, src)
}
func (m *CommonEncodedVotePart) XXX_Size() int {
	return m.Size()
}
func (m *CommonEncodedVotePart) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonEncodedVotePart.DiscardUnknown(m)
}

var xxx_messageInfo_CommonEncodedVotePart proto.InternalMessageInfo

func (m *CommonEncodedVotePart) GetSignedDataPrefix() github_com_cometbft_cometbft_libs_bytes.HexBytes {
	if m != nil {
		return m.SignedDataPrefix
	}
	return nil
}

func (m *CommonEncodedVotePart) GetSignedDataSuffix() github_com_cometbft_cometbft_libs_bytes.HexBytes {
	if m != nil {
		return m.SignedDataSuffix
	}
	return nil
}

func init() {
	proto.RegisterType((*CommonEncodedVotePart)(nil), "cosmonova.client.CommonEncodedVotePart")
}

func init() {
	proto.RegisterFile("cosmonova/client/common_encoded_part.proto", fileDescriptor_3aa65ce86c9780ba)
}

var fileDescriptor_3aa65ce86c9780ba = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4a, 0xce, 0x2f, 0xce,
	0xcd, 0xcf, 0xcb, 0x2f, 0x4b, 0xd4, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x4f, 0xce, 0xcf,
	0xcd, 0xcd, 0xcf, 0x8b, 0x4f, 0xcd, 0x4b, 0xce, 0x4f, 0x49, 0x4d, 0x89, 0x2f, 0x48, 0x2c, 0x2a,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x80, 0xab, 0xd5, 0x83, 0xa8, 0x95, 0x12, 0x49,
	0xcf, 0x4f, 0xcf, 0x07, 0x4b, 0xea, 0x83, 0x58, 0x10, 0x75, 0x4a, 0xf7, 0x19, 0xb9, 0x44, 0x9d,
	0xc1, 0xa6, 0xb8, 0x42, 0x0c, 0x09, 0xcb, 0x2f, 0x49, 0x0d, 0x48, 0x2c, 0x2a, 0x11, 0x4a, 0xe2,
	0x12, 0x2a, 0xce, 0x4c, 0xcf, 0x4b, 0x4d, 0x89, 0x4f, 0x49, 0x2c, 0x49, 0x8c, 0x2f, 0x28, 0x4a,
	0x4d, 0xcb, 0xac, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x71, 0x32, 0xf9, 0x75, 0x4f, 0xde, 0x20,
	0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x17, 0xe4, 0x8e, 0xd4, 0x92, 0xa4, 0xb4,
	0x12, 0x04, 0x23, 0x27, 0x33, 0xa9, 0x58, 0x3f, 0xa9, 0xb2, 0x24, 0xb5, 0x58, 0xcf, 0x23, 0xb5,
	0xc2, 0x09, 0xc4, 0x08, 0x12, 0x80, 0x98, 0xe7, 0x92, 0x58, 0x92, 0x18, 0x00, 0x36, 0x0d, 0xdd,
	0x8e, 0xe2, 0xd2, 0x34, 0x90, 0x1d, 0x4c, 0xd4, 0xb1, 0x23, 0x18, 0x6c, 0x9a, 0x93, 0xd1, 0x89,
	0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3,
	0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x49, 0x20, 0xc2, 0xb3, 0x02, 0x16, 0xa2,
	0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0xe0, 0xc0, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x7d, 0x37, 0x31, 0x9d, 0x72, 0x01, 0x00, 0x00,
}

func (m *CommonEncodedVotePart) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommonEncodedVotePart) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommonEncodedVotePart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignedDataSuffix) > 0 {
		i -= len(m.SignedDataSuffix)
		copy(dAtA[i:], m.SignedDataSuffix)
		i = encodeVarintCommonEncodedPart(dAtA, i, uint64(len(m.SignedDataSuffix)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SignedDataPrefix) > 0 {
		i -= len(m.SignedDataPrefix)
		copy(dAtA[i:], m.SignedDataPrefix)
		i = encodeVarintCommonEncodedPart(dAtA, i, uint64(len(m.SignedDataPrefix)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommonEncodedPart(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommonEncodedPart(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CommonEncodedVotePart) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SignedDataPrefix)
	if l > 0 {
		n += 1 + l + sovCommonEncodedPart(uint64(l))
	}
	l = len(m.SignedDataSuffix)
	if l > 0 {
		n += 1 + l + sovCommonEncodedPart(uint64(l))
	}
	return n
}

func sovCommonEncodedPart(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommonEncodedPart(x uint64) (n int) {
	return sovCommonEncodedPart(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CommonEncodedVotePart) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommonEncodedPart
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommonEncodedVotePart: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommonEncodedVotePart: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedDataPrefix", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommonEncodedPart
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommonEncodedPart
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommonEncodedPart
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedDataPrefix = append(m.SignedDataPrefix[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedDataPrefix == nil {
				m.SignedDataPrefix = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedDataSuffix", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommonEncodedPart
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommonEncodedPart
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommonEncodedPart
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedDataSuffix = append(m.SignedDataSuffix[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedDataSuffix == nil {
				m.SignedDataSuffix = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommonEncodedPart(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommonEncodedPart
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommonEncodedPart(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommonEncodedPart
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommonEncodedPart
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommonEncodedPart
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommonEncodedPart
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommonEncodedPart
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommonEncodedPart
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommonEncodedPart        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommonEncodedPart          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommonEncodedPart = fmt.Errorf("proto: unexpected end of group")
)
